name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build main (gcc)
        run: g++ --version && g++ main.cpp -I include -std=c++17 -Wall -Wextra -pedantic -Werror

      - name: Build main (clang++)
        run: clang++ --version && clang++ main.cpp -I include -std=c++17 -Wall -Wextra -pedantic -Werror
