name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: g++
        run: g++ --version && g++ main.cpp -I include -std=c++17 -O2 -Wall -Wextra -pedantic -Wshadow -Werror

      - name: clang++
        run: clang++ --version && clang++ main.cpp -I include -std=c++17 -O2 -Wall -Wextra -pedantic -Wshadow -Werror

  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: clang-tidy
        run: clang-tidy include/constexpr_hash_map/constexpr_hash_map.hpp main.cpp --checks=bugprone,cert,clang-analyzer,fuchsia,google,misc,modernize,performance,portabiliy,readability --warnings-as-errors="*" -- -I include -std=c++17

  documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: doxygen
        run: sudo apt-get install -y doxygen && doxygen --version && doxygen .doxygen  
